server:
  port: 8088

spring:
  application:
    name: chat
  datasource:
    url: jdbc:mysql://localhost:3306/websocket_chat
    username: root
    password: Ab@230596
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true